# Fetch and self-host the Google Fonts used by JIZURA (one-shot script; output ships with the app).
#
# Usage (proxy must be up first):
#   powershell -ExecutionPolicy Bypass -File tools\fetch-jizura-fonts.ps1
#
# NOTE: this file is deliberately ASCII-only. Windows PowerShell 5.1 reads
# BOM-less .ps1 as ANSI, so non-ASCII text here becomes mojibake and breaks parsing.
#
# 1. fetch css2 with a modern browser UA (Google serves ttf instead of woff2 otherwise)
# 2. download every fonts.gstatic.com woff2 referenced by that CSS
# 3. rewrite the remote URLs to relative paths and merge into vendor\jizura\fonts.css
#
# Safe to re-run: it keeps a raw copy of each family's CSS in css-raw\, so a second
# run does not have to re-fetch 18 x ~450 KB of CSS from Google.

$ErrorActionPreference = 'Stop'
$Proxy = 'http://127.0.0.1:7890'
$Root = Split-Path -Parent $PSScriptRoot
$Dir = Join-Path $Root 'app\web\vendor\jizura'
$FontDir = Join-Path $Dir 'fonts'
$RawDir = Join-Path $Dir 'css-raw'
$UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'

# Every family/weight spec reachable through JIZURA's font catalogue (the gf: fields
# in index.html). Refresh this list when bumping the bundled JIZURA build.
$Specs = @(
  'Dela+Gothic+One'
  'DotGothic16'
  'IBM+Plex+Mono:wght@500;600'
  'IBM+Plex+Sans+JP:wght@400;500;700'
  'Kaisei+Tokumin:wght@800'
  'Kiwi+Maru:wght@500'
  'Klee+One:wght@600'
  'M+PLUS+Rounded+1c:wght@800'
  'Mochiy+Pop+One'
  'Noto+Sans+JP:wght@300;500;700;900'
  'Noto+Serif+JP:wght@300;500;700'
  'Potta+One'
  'Rampart+One'
  'Reggae+One'
  'Shippori+Mincho+B1:wght@800'
  'Yuji+Syuku'
  'Zen+Kaku+Gothic+New:wght@900'
  'Zen+Old+Mincho:wght@900'
)

New-Item -ItemType Directory -Force -Path $FontDir | Out-Null
New-Item -ItemType Directory -Force -Path $RawDir | Out-Null
$env:HTTPS_PROXY = $Proxy

# gstatic paths allow dots inside the file name (....cjb4.85.woff2), so the tail may not
# be greedy across dots: `[^/]+\.woff2` with the \. anchored to the LAST dot only works
# because the name has no dot after it. Keep this pattern in sync with the -replace below.
$UrlRe = 'https://fonts\.gstatic\.com/[A-Za-z0-9/._\-]*?[A-Za-z0-9_\-]\.woff2'

$out = New-Object System.Text.StringBuilder
[void]$out.AppendLine('/* Google Fonts used by JIZURA, self-hosted (SIL Open Font License 1.1).')
[void]$out.AppendLine(' * Generated by tools/fetch-jizura-fonts.ps1 -- do not edit by hand. */')

$all = [System.Collections.Generic.List[string]]::new()
$n = 0
foreach ($spec in $Specs) {
  $n++
  $safe = ($spec -replace '[^A-Za-z0-9]', '_')
  $cache = Join-Path $RawDir "$safe.css"
  if (Test-Path $cache) {
    Write-Host "[$n/$($Specs.Count)] $spec (cached)"
    $css = [System.IO.File]::ReadAllLines($cache, [System.Text.Encoding]::UTF8)
  } else {
    Write-Host "[$n/$($Specs.Count)] $spec"
    $url = "https://fonts.googleapis.com/css2?family=$spec&display=swap"
    $css = & curl.exe -s -x $Proxy --max-time 90 -A $UA $url
    if ($LASTEXITCODE -ne 0 -or -not $css -or ($css -join '') -notmatch [regex]::Escape('@font-face')) {
      throw "no CSS for $spec (curl exit $LASTEXITCODE)"
    }
    [System.IO.File]::WriteAllLines($cache, $css, (New-Object System.Text.UTF8Encoding($false)))
  }
  [void]$out.AppendLine("/* $spec */")
  [void]$out.AppendLine(($css -join "`n"))
  $all.AddRange([string[]]$css)
}

$urls = [regex]::Matches(($all -join "`n"), $UrlRe) |
  ForEach-Object { $_.Value } | Sort-Object -Unique
# 只下还没有的（脚本可重跑）。
# 用显式循环而不是 Where-Object 管道：这一段的管道在 PS 5.1 里行为不好排查，
# 循环写出来是确定的，也方便出错时逐条打印。
$todo = New-Object System.Collections.Generic.List[string]
$leafSeen = New-Object 'System.Collections.Generic.HashSet[string]'
foreach ($u in $urls) {
  $leaf = Split-Path $u -Leaf
  if (-not $leafSeen.Add($leaf)) { continue }        # 同一份文件被多条 @font-face 引用，只下一次
  if (Test-Path (Join-Path $FontDir $leaf)) { continue }
  $todo.Add($u)
}
Write-Host "$($urls.Count) url refs / $($leafSeen.Count) distinct files, $($todo.Count) still to download"

# 串行一个一个下要两个多小时（实测 ~11 个/分钟），必须并发。
# 这台机器的 curl 是 7.55.1，**没有 --parallel**（7.66 才加），所以用 runspace 池并发跑 curl。
$failed = [System.Collections.Generic.List[string]]::new()
if ($todo.Count) {
  $pool = [runspacefactory]::CreateRunspacePool(1, 12)
  $pool.Open()
  $script:FontDir = $FontDir
  $script:Proxy = $Proxy
  $jobs = foreach ($u in $todo) {
    $ps = [powershell]::Create()
    $ps.RunspacePool = $pool
    [void]$ps.AddScript({
      param($u, $dir, $proxy)
      $name = Split-Path $u -Leaf
      $dest = Join-Path $dir $name
      & curl.exe -s -f -x $proxy --max-time 90 -o $dest $u
      if ($LASTEXITCODE -ne 0 -or -not (Test-Path $dest)) { return $u }
      return $null
    }).AddArgument($u).AddArgument($FontDir).AddArgument($Proxy)
    [pscustomobject]@{ PS = $ps; Handle = $ps.BeginInvoke() }
  }
  $done = 0
  foreach ($j in $jobs) {
    $r = $j.PS.EndInvoke($j.Handle)
    $j.PS.Dispose()
    $done++
    if ($r) { $failed.Add([string]$r) }
    if ($done % 200 -eq 0) { Write-Host "  $done / $($todo.Count)" }
  }
  $pool.Close()
  $pool.Dispose()
  Write-Host "  $done / $($todo.Count)"
}

$files = Get-ChildItem $FontDir -File
$bytes = ($files | Measure-Object Length -Sum).Sum

# remote URL -> relative path. fonts.css lives in vendor\jizura\, fonts in vendor\jizura\fonts\
# 用 [regex]::Replace 而不是 `-replace`：PS 5.1 的 -replace 拿脚本块当替换**字面量**，
# 会把 "System.Text.RegularExpressions.MatchEvaluator" 这串字写进 CSS。
$cssFinal = [regex]::Replace($out.ToString(), $UrlRe, { param($m) 'fonts/' + (Split-Path $m.Value -Leaf) })
[System.IO.File]::WriteAllText((Join-Path $Dir 'fonts.css'), $cssFinal, (New-Object System.Text.UTF8Encoding($false)))

$mb = [math]::Round($bytes / 1MB, 1)
Write-Host "done: $($files.Count) files on disk, $($failed.Count) failed, $mb MB -> app\web\vendor\jizura\fonts\"
if ($failed.Count) { $failed | ForEach-Object { Write-Host "  failed: $_" } }
